#import "objd.h"
@class TRTrain;
@class TRTrainType;
@class TRCityColor;
@class TRCarType;
@class EGLocalPlayerScore;
@class EGPlatform;

@class TRStr;
@class TRStrings;
@class TREnStrings;
@class TRRuStrings;
@class TRJpStrings;
@class TRKoStrings;
@class TRChinaStrings;
@class TRPtStrings;
@class TRItStrings;
@class TRSpStrings;
@class TRGeStrings;
@class TRFrStrings;

@interface TRStr : NSObject
- (ODClassType*)type;
+ (TRStrings*)Loc;
+ (ODClassType*)type;
@end


@interface TRStrings : NSObject {
@private
    NSString* _language;
}
@property (nonatomic, readonly) NSString* language;

+ (instancetype)stringsWithLanguage:(NSString*)language;
- (instancetype)initWithLanguage:(NSString*)language;
- (ODClassType*)type;
- (NSString*)formatCost:(NSInteger)cost;
- (NSString*)notificationsCharSet;
- (NSString*)levelNumber:(NSUInteger)number;
- (NSString*)startLevelNumber:(NSUInteger)number;
- (NSString*)railBuiltCost:(NSInteger)cost;
- (NSString*)railRemovedCost:(NSInteger)cost;
- (NSString*)trainArrivedTrain:(TRTrain*)train cost:(NSInteger)cost;
- (NSString*)trainDestroyedCost:(NSInteger)cost;
- (NSString*)trainDelayedFineTrain:(TRTrain*)train cost:(NSInteger)cost;
- (NSString*)damageFixedPaymentCost:(NSInteger)cost;
- (NSString*)cityBuilt;
- (NSString*)menuButtonsCharacterSet;
- (NSString*)resumeGame;
- (NSString*)restartLevel:(NSUInteger)level;
- (NSString*)replayLevel:(NSUInteger)level;
- (NSString*)goToNextLevel:(NSUInteger)level;
- (NSString*)chooseLevel;
- (NSString*)supportButton;
- (NSString*)shareButton;
- (NSString*)leaderboard;
- (NSString*)buyButton;
- (NSString*)victory;
- (NSString*)defeat;
- (NSString*)moneyOver;
- (NSString*)result;
- (NSString*)best;
- (NSString*)error;
- (NSString*)supportEmailText;
- (NSString*)rateText;
- (NSString*)rateNow;
- (NSString*)rateProblem;
- (NSString*)rateLater;
- (NSString*)rateClose;
- (NSString*)topScore:(EGLocalPlayerScore*)score;
- (NSString*)tapToContinue;
- (NSString*)colorOrange;
- (NSString*)colorGreen;
- (NSString*)colorPink;
- (NSString*)colorPurple;
- (NSString*)colorGrey;
- (NSString*)colorBlue;
- (NSString*)colorMint;
- (NSString*)colorRed;
- (NSString*)colorBeige;
- (NSString*)colorYellow;
- (NSString*)helpConnectTwoCities;
- (NSString*)helpRules;
- (NSString*)helpNewCity;
- (NSString*)helpSporadicDamage;
- (NSString*)helpDamage;
- (NSString*)helpRepairer;
- (NSString*)helpCrazy;
- (NSString*)helpInZoom;
- (NSString*)helpExpressTrain;
- (NSString*)helpTrainTo:(NSString*)to;
- (NSString*)helpTrainWithSwitchesTo:(NSString*)to;
- (NSString*)helpToMakeZoom;
- (NSString*)helpToRemove;
- (NSString*)linesAdvice;
- (NSString*)helpSlowMotion;
- (NSString*)shareTextUrl:(NSString*)url;
- (NSString*)shareSubject;
- (NSString*)twitterTextUrl:(NSString*)url;
+ (ODClassType*)type;
@end


@interface TREnStrings : TRStrings
+ (instancetype)enStrings;
- (instancetype)init;
- (ODClassType*)type;
- (NSString*)levelNumber:(NSUInteger)number;
- (NSString*)railBuiltCost:(NSInteger)cost;
- (NSString*)trainArrivedTrain:(TRTrain*)train cost:(NSInteger)cost;
- (NSString*)trainDestroyedCost:(NSInteger)cost;
- (NSString*)trainDelayedFineTrain:(TRTrain*)train cost:(NSInteger)cost;
- (NSString*)damageFixedPaymentCost:(NSInteger)cost;
- (NSString*)resumeGame;
- (NSString*)restartLevel:(NSUInteger)level;
- (NSString*)replayLevel:(NSUInteger)level;
- (NSString*)goToNextLevel:(NSUInteger)level;
- (NSString*)chooseLevel;
- (NSString*)victory;
- (NSString*)defeat;
- (NSString*)moneyOver;
- (NSString*)cityBuilt;
- (NSString*)tapToContinue;
- (NSString*)error;
- (NSString*)buyButton;
- (NSString*)shareButton;
- (NSString*)supportButton;
- (NSString*)rateText;
- (NSString*)rateNow;
- (NSString*)rateProblem;
- (NSString*)rateLater;
- (NSString*)rateClose;
- (NSString*)helpConnectTwoCities;
- (NSString*)helpRules;
- (NSString*)helpNewCity;
- (NSString*)helpTrainTo:(NSString*)to;
- (NSString*)helpTrainWithSwitchesTo:(NSString*)to;
- (NSString*)helpExpressTrain;
- (NSString*)helpToMakeZoom;
- (NSString*)helpInZoom;
- (NSString*)helpSporadicDamage;
- (NSString*)helpDamage;
- (NSString*)helpCrazy;
- (NSString*)helpRepairer;
- (NSString*)helpSlowMotion;
- (NSString*)linesAdvice;
- (NSString*)result;
- (NSString*)best;
- (NSString*)topScore:(EGLocalPlayerScore*)score;
- (NSString*)leaderboard;
- (NSString*)shareSubject;
- (NSString*)shareTextUrl:(NSString*)url;
- (NSString*)twitterTextUrl:(NSString*)url;
+ (ODClassType*)type;
@end


@interface TRRuStrings : TRStrings
+ (instancetype)ruStrings;
- (instancetype)init;
- (ODClassType*)type;
- (NSString*)railRemovedCost:(NSInteger)cost;
- (NSString*)helpToRemove;
- (NSString*)levelNumber:(NSUInteger)number;
- (NSString*)railBuiltCost:(NSInteger)cost;
- (NSString*)trainArrivedTrain:(TRTrain*)train cost:(NSInteger)cost;
- (NSString*)trainDestroyedCost:(NSInteger)cost;
- (NSString*)trainDelayedFineTrain:(TRTrain*)train cost:(NSInteger)cost;
- (NSString*)damageFixedPaymentCost:(NSInteger)cost;
- (NSString*)resumeGame;
- (NSString*)restartLevel:(NSUInteger)level;
- (NSString*)replayLevel:(NSUInteger)level;
- (NSString*)goToNextLevel:(NSUInteger)level;
- (NSString*)chooseLevel;
- (NSString*)victory;
- (NSString*)defeat;
- (NSString*)moneyOver;
- (NSString*)cityBuilt;
- (NSString*)tapToContinue;
- (NSString*)error;
- (NSString*)buyButton;
- (NSString*)colorOrange;
- (NSString*)colorGreen;
- (NSString*)colorPink;
- (NSString*)colorPurple;
- (NSString*)colorGrey;
- (NSString*)colorBlue;
- (NSString*)colorMint;
- (NSString*)colorRed;
- (NSString*)colorBeige;
- (NSString*)colorYellow;
- (NSString*)helpConnectTwoCities;
- (NSString*)helpNewCity;
- (NSString*)helpTrainTo:(NSString*)to;
- (NSString*)helpTrainWithSwitchesTo:(NSString*)to;
- (NSString*)helpExpressTrain;
- (NSString*)helpToMakeZoom;
- (NSString*)helpInZoom;
- (NSString*)helpRules;
- (NSString*)helpSporadicDamage;
- (NSString*)helpDamage;
- (NSString*)helpRepairer;
- (NSString*)helpCrazy;
- (NSString*)linesAdvice;
- (NSString*)helpSlowMotion;
- (NSString*)shareButton;
- (NSString*)supportButton;
- (NSString*)supportEmailText;
- (NSString*)rateText;
- (NSString*)rateNow;
- (NSString*)rateProblem;
- (NSString*)rateLater;
- (NSString*)rateClose;
- (NSString*)result;
- (NSString*)best;
- (NSString*)topScore:(EGLocalPlayerScore*)score;
- (NSString*)leaderboard;
- (NSString*)shareSubject;
- (NSString*)shareTextUrl:(NSString*)url;
- (NSString*)twitterTextUrl:(NSString*)url;
+ (ODClassType*)type;
@end


@interface TRJpStrings : TRStrings
+ (instancetype)jpStrings;
- (instancetype)init;
- (ODClassType*)type;
- (NSString*)railRemovedCost:(NSInteger)cost;
- (NSString*)helpToRemove;
- (NSString*)levelNumber:(NSUInteger)number;
- (NSString*)railBuiltCost:(NSInteger)cost;
- (NSString*)trainArrivedTrain:(TRTrain*)train cost:(NSInteger)cost;
- (NSString*)trainDestroyedCost:(NSInteger)cost;
- (NSString*)trainDelayedFineTrain:(TRTrain*)train cost:(NSInteger)cost;
- (NSString*)damageFixedPaymentCost:(NSInteger)cost;
- (NSString*)resumeGame;
- (NSString*)restartLevel:(NSUInteger)level;
- (NSString*)replayLevel:(NSUInteger)level;
- (NSString*)goToNextLevel:(NSUInteger)level;
- (NSString*)chooseLevel;
- (NSString*)victory;
- (NSString*)defeat;
- (NSString*)moneyOver;
- (NSString*)cityBuilt;
- (NSString*)tapToContinue;
- (NSString*)error;
- (NSString*)buyButton;
- (NSString*)shareButton;
- (NSString*)supportButton;
- (NSString*)rateText;
- (NSString*)rateNow;
- (NSString*)rateProblem;
- (NSString*)rateLater;
- (NSString*)rateClose;
- (NSString*)helpConnectTwoCities;
- (NSString*)helpRules;
- (NSString*)helpNewCity;
- (NSString*)helpTrainTo:(NSString*)to;
- (NSString*)helpTrainWithSwitchesTo:(NSString*)to;
- (NSString*)helpExpressTrain;
- (NSString*)helpToMakeZoom;
- (NSString*)helpInZoom;
- (NSString*)helpSporadicDamage;
- (NSString*)helpDamage;
- (NSString*)helpCrazy;
- (NSString*)helpRepairer;
- (NSString*)helpSlowMotion;
- (NSString*)linesAdvice;
- (NSString*)result;
- (NSString*)best;
- (NSString*)topScore:(EGLocalPlayerScore*)score;
- (NSString*)leaderboard;
- (NSString*)shareSubject;
- (NSString*)shareTextUrl:(NSString*)url;
- (NSString*)twitterTextUrl:(NSString*)url;
+ (ODClassType*)type;
@end


@interface TRKoStrings : TRStrings
+ (instancetype)koStrings;
- (instancetype)init;
- (ODClassType*)type;
- (NSString*)railRemovedCost:(NSInteger)cost;
- (NSString*)helpToRemove;
- (NSString*)levelNumber:(NSUInteger)number;
- (NSString*)railBuiltCost:(NSInteger)cost;
- (NSString*)trainArrivedTrain:(TRTrain*)train cost:(NSInteger)cost;
- (NSString*)trainDestroyedCost:(NSInteger)cost;
- (NSString*)trainDelayedFineTrain:(TRTrain*)train cost:(NSInteger)cost;
- (NSString*)damageFixedPaymentCost:(NSInteger)cost;
- (NSString*)resumeGame;
- (NSString*)restartLevel:(NSUInteger)level;
- (NSString*)replayLevel:(NSUInteger)level;
- (NSString*)goToNextLevel:(NSUInteger)level;
- (NSString*)chooseLevel;
- (NSString*)victory;
- (NSString*)defeat;
- (NSString*)moneyOver;
- (NSString*)cityBuilt;
- (NSString*)tapToContinue;
- (NSString*)error;
- (NSString*)buyButton;
- (NSString*)shareButton;
- (NSString*)supportButton;
- (NSString*)rateText;
- (NSString*)rateNow;
- (NSString*)rateProblem;
- (NSString*)rateLater;
- (NSString*)rateClose;
- (NSString*)helpConnectTwoCities;
- (NSString*)helpRules;
- (NSString*)helpNewCity;
- (NSString*)helpTrainTo:(NSString*)to;
- (NSString*)helpTrainWithSwitchesTo:(NSString*)to;
- (NSString*)helpExpressTrain;
- (NSString*)helpToMakeZoom;
- (NSString*)helpInZoom;
- (NSString*)helpSporadicDamage;
- (NSString*)helpDamage;
- (NSString*)helpCrazy;
- (NSString*)helpRepairer;
- (NSString*)helpSlowMotion;
- (NSString*)linesAdvice;
- (NSString*)result;
- (NSString*)best;
- (NSString*)topScore:(EGLocalPlayerScore*)score;
- (NSString*)leaderboard;
- (NSString*)shareSubject;
- (NSString*)shareTextUrl:(NSString*)url;
- (NSString*)twitterTextUrl:(NSString*)url;
+ (ODClassType*)type;
@end


@interface TRChinaStrings : TRStrings
+ (instancetype)chinaStrings;
- (instancetype)init;
- (ODClassType*)type;
- (NSString*)railRemovedCost:(NSInteger)cost;
- (NSString*)helpToRemove;
- (NSString*)levelNumber:(NSUInteger)number;
- (NSString*)railBuiltCost:(NSInteger)cost;
- (NSString*)trainArrivedTrain:(TRTrain*)train cost:(NSInteger)cost;
- (NSString*)trainDestroyedCost:(NSInteger)cost;
- (NSString*)trainDelayedFineTrain:(TRTrain*)train cost:(NSInteger)cost;
- (NSString*)damageFixedPaymentCost:(NSInteger)cost;
- (NSString*)resumeGame;
- (NSString*)restartLevel:(NSUInteger)level;
- (NSString*)replayLevel:(NSUInteger)level;
- (NSString*)goToNextLevel:(NSUInteger)level;
- (NSString*)chooseLevel;
- (NSString*)victory;
- (NSString*)defeat;
- (NSString*)moneyOver;
- (NSString*)cityBuilt;
- (NSString*)tapToContinue;
- (NSString*)error;
- (NSString*)buyButton;
- (NSString*)shareButton;
- (NSString*)supportButton;
- (NSString*)rateText;
- (NSString*)rateNow;
- (NSString*)rateProblem;
- (NSString*)rateLater;
- (NSString*)rateClose;
- (NSString*)helpConnectTwoCities;
- (NSString*)helpRules;
- (NSString*)helpNewCity;
- (NSString*)helpTrainTo:(NSString*)to;
- (NSString*)helpTrainWithSwitchesTo:(NSString*)to;
- (NSString*)helpExpressTrain;
- (NSString*)helpToMakeZoom;
- (NSString*)helpInZoom;
- (NSString*)helpSporadicDamage;
- (NSString*)helpDamage;
- (NSString*)helpCrazy;
- (NSString*)helpRepairer;
- (NSString*)helpSlowMotion;
- (NSString*)linesAdvice;
- (NSString*)result;
- (NSString*)best;
- (NSString*)topScore:(EGLocalPlayerScore*)score;
- (NSString*)leaderboard;
- (NSString*)shareSubject;
- (NSString*)shareTextUrl:(NSString*)url;
- (NSString*)twitterTextUrl:(NSString*)url;
+ (ODClassType*)type;
@end


@interface TRPtStrings : TRStrings
+ (instancetype)ptStrings;
- (instancetype)init;
- (ODClassType*)type;
- (NSString*)railRemovedCost:(NSInteger)cost;
- (NSString*)helpToRemove;
- (NSString*)levelNumber:(NSUInteger)number;
- (NSString*)railBuiltCost:(NSInteger)cost;
- (NSString*)trainArrivedTrain:(TRTrain*)train cost:(NSInteger)cost;
- (NSString*)trainDestroyedCost:(NSInteger)cost;
- (NSString*)trainDelayedFineTrain:(TRTrain*)train cost:(NSInteger)cost;
- (NSString*)damageFixedPaymentCost:(NSInteger)cost;
- (NSString*)resumeGame;
- (NSString*)restartLevel:(NSUInteger)level;
- (NSString*)replayLevel:(NSUInteger)level;
- (NSString*)goToNextLevel:(NSUInteger)level;
- (NSString*)chooseLevel;
- (NSString*)victory;
- (NSString*)defeat;
- (NSString*)moneyOver;
- (NSString*)cityBuilt;
- (NSString*)tapToContinue;
- (NSString*)error;
- (NSString*)buyButton;
- (NSString*)shareButton;
- (NSString*)supportButton;
- (NSString*)rateText;
- (NSString*)rateNow;
- (NSString*)rateProblem;
- (NSString*)rateLater;
- (NSString*)rateClose;
- (NSString*)helpConnectTwoCities;
- (NSString*)helpRules;
- (NSString*)helpNewCity;
- (NSString*)helpTrainTo:(NSString*)to;
- (NSString*)helpTrainWithSwitchesTo:(NSString*)to;
- (NSString*)helpExpressTrain;
- (NSString*)helpToMakeZoom;
- (NSString*)helpInZoom;
- (NSString*)helpSporadicDamage;
- (NSString*)helpDamage;
- (NSString*)helpCrazy;
- (NSString*)helpRepairer;
- (NSString*)helpSlowMotion;
- (NSString*)linesAdvice;
- (NSString*)result;
- (NSString*)best;
- (NSString*)topScore:(EGLocalPlayerScore*)score;
- (NSString*)leaderboard;
- (NSString*)shareSubject;
- (NSString*)shareTextUrl:(NSString*)url;
- (NSString*)twitterTextUrl:(NSString*)url;
+ (ODClassType*)type;
@end


@interface TRItStrings : TRStrings
+ (instancetype)itStrings;
- (instancetype)init;
- (ODClassType*)type;
- (NSString*)railRemovedCost:(NSInteger)cost;
- (NSString*)helpToRemove;
- (NSString*)levelNumber:(NSUInteger)number;
- (NSString*)railBuiltCost:(NSInteger)cost;
- (NSString*)trainArrivedTrain:(TRTrain*)train cost:(NSInteger)cost;
- (NSString*)trainDestroyedCost:(NSInteger)cost;
- (NSString*)trainDelayedFineTrain:(TRTrain*)train cost:(NSInteger)cost;
- (NSString*)damageFixedPaymentCost:(NSInteger)cost;
- (NSString*)resumeGame;
- (NSString*)restartLevel:(NSUInteger)level;
- (NSString*)replayLevel:(NSUInteger)level;
- (NSString*)goToNextLevel:(NSUInteger)level;
- (NSString*)chooseLevel;
- (NSString*)victory;
- (NSString*)defeat;
- (NSString*)moneyOver;
- (NSString*)cityBuilt;
- (NSString*)tapToContinue;
- (NSString*)error;
- (NSString*)buyButton;
- (NSString*)shareButton;
- (NSString*)supportButton;
- (NSString*)rateText;
- (NSString*)rateNow;
- (NSString*)rateProblem;
- (NSString*)rateLater;
- (NSString*)rateClose;
- (NSString*)helpConnectTwoCities;
- (NSString*)helpRules;
- (NSString*)helpNewCity;
- (NSString*)helpTrainTo:(NSString*)to;
- (NSString*)helpTrainWithSwitchesTo:(NSString*)to;
- (NSString*)helpExpressTrain;
- (NSString*)helpToMakeZoom;
- (NSString*)helpInZoom;
- (NSString*)helpSporadicDamage;
- (NSString*)helpDamage;
- (NSString*)helpCrazy;
- (NSString*)helpRepairer;
- (NSString*)helpSlowMotion;
- (NSString*)linesAdvice;
- (NSString*)result;
- (NSString*)best;
- (NSString*)topScore:(EGLocalPlayerScore*)score;
- (NSString*)leaderboard;
- (NSString*)shareSubject;
- (NSString*)shareTextUrl:(NSString*)url;
- (NSString*)twitterTextUrl:(NSString*)url;
+ (ODClassType*)type;
@end


@interface TRSpStrings : TRStrings
+ (instancetype)spStrings;
- (instancetype)init;
- (ODClassType*)type;
- (NSString*)railRemovedCost:(NSInteger)cost;
- (NSString*)helpToRemove;
- (NSString*)levelNumber:(NSUInteger)number;
- (NSString*)railBuiltCost:(NSInteger)cost;
- (NSString*)trainArrivedTrain:(TRTrain*)train cost:(NSInteger)cost;
- (NSString*)trainDestroyedCost:(NSInteger)cost;
- (NSString*)trainDelayedFineTrain:(TRTrain*)train cost:(NSInteger)cost;
- (NSString*)damageFixedPaymentCost:(NSInteger)cost;
- (NSString*)resumeGame;
- (NSString*)restartLevel:(NSUInteger)level;
- (NSString*)replayLevel:(NSUInteger)level;
- (NSString*)goToNextLevel:(NSUInteger)level;
- (NSString*)chooseLevel;
- (NSString*)victory;
- (NSString*)defeat;
- (NSString*)moneyOver;
- (NSString*)cityBuilt;
- (NSString*)tapToContinue;
- (NSString*)error;
- (NSString*)buyButton;
- (NSString*)shareButton;
- (NSString*)supportButton;
- (NSString*)rateText;
- (NSString*)rateNow;
- (NSString*)rateProblem;
- (NSString*)rateLater;
- (NSString*)rateClose;
- (NSString*)helpConnectTwoCities;
- (NSString*)helpRules;
- (NSString*)helpNewCity;
- (NSString*)helpTrainTo:(NSString*)to;
- (NSString*)helpTrainWithSwitchesTo:(NSString*)to;
- (NSString*)helpExpressTrain;
- (NSString*)helpToMakeZoom;
- (NSString*)helpInZoom;
- (NSString*)helpSporadicDamage;
- (NSString*)helpDamage;
- (NSString*)helpCrazy;
- (NSString*)helpRepairer;
- (NSString*)helpSlowMotion;
- (NSString*)linesAdvice;
- (NSString*)result;
- (NSString*)best;
- (NSString*)topScore:(EGLocalPlayerScore*)score;
- (NSString*)leaderboard;
- (NSString*)shareSubject;
- (NSString*)shareTextUrl:(NSString*)url;
- (NSString*)twitterTextUrl:(NSString*)url;
+ (ODClassType*)type;
@end


@interface TRGeStrings : TRStrings
+ (instancetype)geStrings;
- (instancetype)init;
- (ODClassType*)type;
- (NSString*)railRemovedCost:(NSInteger)cost;
- (NSString*)helpToRemove;
- (NSString*)levelNumber:(NSUInteger)number;
- (NSString*)railBuiltCost:(NSInteger)cost;
- (NSString*)trainArrivedTrain:(TRTrain*)train cost:(NSInteger)cost;
- (NSString*)trainDestroyedCost:(NSInteger)cost;
- (NSString*)trainDelayedFineTrain:(TRTrain*)train cost:(NSInteger)cost;
- (NSString*)damageFixedPaymentCost:(NSInteger)cost;
- (NSString*)resumeGame;
- (NSString*)restartLevel:(NSUInteger)level;
- (NSString*)replayLevel:(NSUInteger)level;
- (NSString*)goToNextLevel:(NSUInteger)level;
- (NSString*)chooseLevel;
- (NSString*)victory;
- (NSString*)defeat;
- (NSString*)moneyOver;
- (NSString*)cityBuilt;
- (NSString*)tapToContinue;
- (NSString*)error;
- (NSString*)buyButton;
- (NSString*)shareButton;
- (NSString*)supportButton;
- (NSString*)rateText;
- (NSString*)rateNow;
- (NSString*)rateProblem;
- (NSString*)rateLater;
- (NSString*)rateClose;
- (NSString*)helpConnectTwoCities;
- (NSString*)helpRules;
- (NSString*)helpNewCity;
- (NSString*)helpTrainTo:(NSString*)to;
- (NSString*)helpTrainWithSwitchesTo:(NSString*)to;
- (NSString*)helpExpressTrain;
- (NSString*)helpToMakeZoom;
- (NSString*)helpInZoom;
- (NSString*)helpSporadicDamage;
- (NSString*)helpDamage;
- (NSString*)helpCrazy;
- (NSString*)helpRepairer;
- (NSString*)helpSlowMotion;
- (NSString*)linesAdvice;
- (NSString*)result;
- (NSString*)best;
- (NSString*)topScore:(EGLocalPlayerScore*)score;
- (NSString*)leaderboard;
- (NSString*)shareSubject;
- (NSString*)shareTextUrl:(NSString*)url;
- (NSString*)twitterTextUrl:(NSString*)url;
+ (ODClassType*)type;
@end


@interface TRFrStrings : TRStrings
+ (instancetype)frStrings;
- (instancetype)init;
- (ODClassType*)type;
- (NSString*)railRemovedCost:(NSInteger)cost;
- (NSString*)helpToRemove;
- (NSString*)levelNumber:(NSUInteger)number;
- (NSString*)railBuiltCost:(NSInteger)cost;
- (NSString*)trainArrivedTrain:(TRTrain*)train cost:(NSInteger)cost;
- (NSString*)trainDestroyedCost:(NSInteger)cost;
- (NSString*)trainDelayedFineTrain:(TRTrain*)train cost:(NSInteger)cost;
- (NSString*)damageFixedPaymentCost:(NSInteger)cost;
- (NSString*)resumeGame;
- (NSString*)restartLevel:(NSUInteger)level;
- (NSString*)replayLevel:(NSUInteger)level;
- (NSString*)goToNextLevel:(NSUInteger)level;
- (NSString*)chooseLevel;
- (NSString*)victory;
- (NSString*)defeat;
- (NSString*)moneyOver;
- (NSString*)cityBuilt;
- (NSString*)tapToContinue;
- (NSString*)error;
- (NSString*)buyButton;
- (NSString*)shareButton;
- (NSString*)supportButton;
- (NSString*)rateText;
- (NSString*)rateNow;
- (NSString*)rateProblem;
- (NSString*)rateLater;
- (NSString*)rateClose;
- (NSString*)helpConnectTwoCities;
- (NSString*)helpRules;
- (NSString*)helpNewCity;
- (NSString*)helpTrainTo:(NSString*)to;
- (NSString*)helpTrainWithSwitchesTo:(NSString*)to;
- (NSString*)helpExpressTrain;
- (NSString*)helpToMakeZoom;
- (NSString*)helpInZoom;
- (NSString*)helpSporadicDamage;
- (NSString*)helpDamage;
- (NSString*)helpCrazy;
- (NSString*)helpRepairer;
- (NSString*)helpSlowMotion;
- (NSString*)linesAdvice;
- (NSString*)result;
- (NSString*)best;
- (NSString*)topScore:(EGLocalPlayerScore*)score;
- (NSString*)leaderboard;
- (NSString*)shareSubject;
- (NSString*)shareTextUrl:(NSString*)url;
- (NSString*)twitterTextUrl:(NSString*)url;
+ (ODClassType*)type;
@end


