// Headerfile *.h (generated by Cheetah3D)
//
// There are the following name conventions:
// 	NAME			=name of the object in Cheetah3D. Caution!! Avoid giving two objects the same name
// 	NAME_vertex		=float array which contains the vertex,normal and uvcoord data 
// 	NAME_index		=int array which contains the polygon index data
// 	NAME_vertexcount	=number of vertices
// 	NAME_polygoncount	=number of triangles
//
// The vertex data is saved in the following format:
// 	u0,v0,normalx0,normaly0,normalz0,x0,y0,z0
// 	u1,v1,normalx1,normaly1,normalz1,x1,y1,z1
// 	u2,v2,normalx2,normaly2,normalz2,x2,y2,z2
// 	...
// You can draw the mesh the following way:
// 	glEnableClientState(GL_INDEX_ARRAY);
// 	glEnableClientState(GL_NORMAL_ARRAY);
// 	glEnableClientState(GL_VERTEX_ARRAY);
// 	glEnableClientState(GL_TEXTURE_COORD_ARRAY);
// 	glInterleavedArrays(GL_T2F_N3F_V3F,0,NAME_vertex);
// 	glDrawElements(GL_TRIANGLES,NAME_polygoncount*3,GL_UNSIGNED_INT,NAME_index);
//

#define RailTurn_vertexcount 	12
#define RailTurn_polygoncount 	10


static float RailTurn_vertex[RailTurn_vertexcount][8]={
		{0.00000, 0.00000, -0.00083, 1.00000, -0.00083, 0.33803, 0.00507, 0.14057},
		{0.00000, 0.00000, -0.00167, 1.00000, -0.00106, 0.20589, 0.00505, 0.24356},
		{0.00000, 0.00000, -0.00150, 1.00000, -0.00089, 0.16073, 0.00473, 0.00577},
		{0.00000, 0.00000, -0.00025, 1.00000, -0.00054, 0.49976, 0.00504, 0.09992},
		{0.00000, 0.00000, -0.00064, 1.00000, -0.00055, 0.30966, 0.00490, -0.06851},
		{0.00000, 0.00000, -0.00045, 1.00000, -0.00030, 0.50145, 0.00498, -0.09834},
		{0.00000, 0.00000, -0.00197, 1.00000, -0.00105, 0.03886, 0.00459, 0.11719},
		{0.00000, 0.00000, -0.00177, 1.00000, -0.00098, 0.12273, 0.00502, 0.36183},
		{0.00000, 0.00000, -0.00177, 1.00000, -0.00135, -0.04863, 0.00458, 0.25877},
		{0.00000, 0.00000, -0.00080, 1.00000, -0.00120, 0.10171, 0.00500, 0.50042},
		{0.00000, 0.00000, -0.00001, 1.00000, -0.00230, -0.09949, 0.00500, 0.50056},
		{0.00000, 0.00000, -0.00107, 1.00000, -0.00134, -0.08425, 0.00469, 0.36646},
		};


static int RailTurn_index[RailTurn_polygoncount][3]={
		{0, 1, 2},
		{3, 0, 4},
		{3, 4, 5},
		{1, 6, 2},
		{7, 8, 6},
		{9, 10, 11},
		{1, 7, 6},
		{0, 2, 4},
		{7, 9, 11},
		{7, 11, 8},
		};


