#import "objd.h"
@class EGPlatform;
@class DTLocalKeyValueStorage;
@class DTConflict;
@class DTCloudKeyValueStorage;
@class TRLevel;
@class TestFlight;
@class TRScore;
@class EGGameCenter;
@class TRStr;
@protocol TRStrings;
@class EGSchedule;
@class TRTrain;
@class TRTrainType;
@class TRLevelFactory;
@class EGCameraIsoMove;
@class EGDirector;
@class EGScene;
@protocol EGController;
@class EGInApp;
@class EGInAppTransactionState;
@class EGInAppTransaction;
@class EGAlert;
@class SDSoundDirector;
@class EGRate;
@class EGLocalPlayerScore;
@class TRSceneFactory;
@class TRLevelChooseMenu;
@class EGEMail;
@class EGCounter;
@class EGInAppProduct;
@class EGLengthCounter;
@class EGShareDialog;
@class EGShareContent;
@class EGShareChannel;

@class TRGameDirector;

@interface TRGameDirector : NSObject
@property (nonatomic, readonly) NSString* gameCenterPrefix;
@property (nonatomic, readonly) NSString* gameCenterAchievementPrefix;
@property (nonatomic, readonly) NSString* inAppPrefix;
@property (nonatomic, readonly) NSString* cloudPrefix;
@property (nonatomic, readonly) id<CNSeq> slowMotionsInApp;
@property (nonatomic, readonly) NSInteger maxDaySlowMotions;
@property (nonatomic, readonly) NSInteger slowMotionRestorePeriod;
@property (nonatomic, readonly) DTLocalKeyValueStorage* local;
@property (nonatomic, readonly) id(^resolveMaxLevel)(id, id);
@property (nonatomic, readonly) DTCloudKeyValueStorage* cloud;

+ (id)gameDirector;
- (id)init;
- (ODClassType*)type;
- (void)clearTutorial;
- (NSInteger)bestScoreLevelNumber:(NSUInteger)levelNumber;
- (void)destroyTrainsTrains:(id<CNSeq>)trains;
- (void)_init;
- (void)localPlayerScoreLevel:(NSUInteger)level callback:(void(^)(id))callback;
- (NSInteger)currentLevel;
- (NSInteger)maxAvailableLevel;
- (void)restoreLastScene;
- (void)restartLevel;
- (void)chooseLevel;
- (void)nextLevel;
- (void)rateLater;
- (void)rateClose;
- (void)setLevel:(NSInteger)level;
- (void)showLeaderboardLevel:(TRLevel*)level;
- (void)synchronize;
- (void)showSupportChangeLevel:(BOOL)changeLevel;
- (BOOL)isNeedRate;
- (void)showRate;
- (BOOL)soundEnabled;
- (void)setSoundEnabled:(BOOL)soundEnabled;
- (id<CNSeq>)lastSlowMotions;
- (NSInteger)daySlowMotions;
- (NSInteger)boughtSlowMotions;
- (NSInteger)slowMotionsCount;
- (void)runSlowMotionLevel:(TRLevel*)level;
- (void)checkLastSlowMotions;
- (EGShareDialog*)shareDialog;
- (void)buySlowMotionsProduct:(EGInAppProduct*)product;
- (void)boughtSlowMotionsCount:(NSUInteger)count;
- (void)share;
- (BOOL)isShareToFacebookAvailable;
- (void)shareToFacebook;
- (BOOL)isShareToTwitterAvailable;
- (void)shareToTwitter;
- (id<CNSeq>)slowMotionPrices;
- (void)forLevelF:(void(^)(TRLevel*))f;
- (void)closeShop;
+ (TRGameDirector*)instance;
+ (CNNotificationHandle*)playerScoreRetrieveNotification;
+ (NSInteger)facebookShareRate;
+ (NSInteger)twitterShareRate;
+ (ODClassType*)type;
@end


